### ISSUE TITLE
Deploy All-in-1 Horizon fails on ubuntu 20.04

### ISSUE THREAD

**Issue by girishkumarbk** [open-horizon/devops#50] opened 2021-04-14 11:17 UTC
root@ip-10-0-0-122:~# curl -sSL https://raw.githubusercontent.com/open-horizon/devops/master/mgmt-hub/deploy-mgmt-hub.sh | bash
----------- Verifying input and the host OS...
Error: the host must be Ubuntu 18.x (amd64, ppc64le) or Ubuntu 20.x (amd64, ppc64le) or macOS or RedHat 7.9 (ppc64le) or RedHat 8.3 (ppc64le)
root@ip-10-0-0-122:~# 
root@ip-10-0-0-122:~# 
root@ip-10-0-0-122:~# 
root@ip-10-0-0-122:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
root@ip-10-0-0-122:~# 
root@ip-10-0-0-122:~# DISTRO=${DISTRO:-$(. /etc/os-release 2>/dev/null;echo $ID $VERSION_ID)}
root@ip-10-0-0-122:~# 
root@ip-10-0-0-122:~# 
root@ip-10-0-0-122:~# echo $DISTRO
ubuntu 20.04
root@ip-10-0-0-122:~# 
root@ip-10-0-0-122:~#

**Comment by girishkumarbk** [comment] 2021-04-14 11:18
root@ip-10-0-0-122:~# curl -sSL https://raw.githubusercontent.com/open-horizon/devops/master/mgmt-hub/deploy-mgmt-hub.sh | bash
----------- Verifying input and the host OS...
Error: the host must be Ubuntu 18.x (amd64, ppc64le) or Ubuntu 20.x (amd64, ppc64le) or macOS or RedHat 7.9 (ppc64le) or RedHat 8.3 (ppc64le)
root@ip-10-0-0-122:~# 
root@ip-10-0-0-122:~# 
root@ip-10-0-0-122:~# 
root@ip-10-0-0-122:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
root@ip-10-0-0-122:~# 
root@ip-10-0-0-122:~# DISTRO=${DISTRO:-$(. /etc/os-release 2>/dev/null;echo $ID $VERSION_ID)}
root@ip-10-0-0-122:~# 
root@ip-10-0-0-122:~# 
root@ip-10-0-0-122:~# echo $DISTRO
ubuntu 20.04
root@ip-10-0-0-122:~# 
root@ip-10-0-0-122:~#

**Comment by bmpotter** [comment] 2021-04-14 12:41
This bug was caused by a previously committed PR. I'll fix this soon, hopefully by the end of today.

**Comment by bmpotter** [comment] 2021-04-15 14:43
@girishkumarbk please test this, and if it fixes the problem, comment here and close the issue.

**Closed** 2021-08-25 12:26 UTC
Labels: PR submitted
